# Generated by Django 2.1.4 on 2018-12-06 14:06

from django.db import migrations

PRODUCTS = [ ]


def add_products(apps, schema_editor):
    Product = apps.get_model('shop', 'Product')

    for p in PRODUCTS:
        l = Product.objects.get_or_create(
            name = p['name'],
            price = p['price'],
            slug = p['slug'],
            description = p['description'],
        )

        print(p)


def remove_products(apps, schema_editor):
    Product = apps.get_model('shop', 'Product')

    for p in PRODUCTS:
        l = Product.objects.get(
            slug=p['slug'],
        )

        l.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_products, remove_products)
    ]
