# Generated by Django 2.2.1 on 2019-06-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20190607_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ext_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='inter_price',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='user_type',
            field=models.CharField(default='E', max_length=100),
            preserve_default=False,
        ),
    ]
