# Generated by Django 2.2.2 on 2019-06-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ticket_type',
            field=models.CharField(default='E', max_length=50),
            preserve_default=False,
        ),
    ]
