# Generated by Django 2.2.2 on 2019-06-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_ticket_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ticket_type',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='ticket_type',
            field=models.CharField(default='E', max_length=50),
            preserve_default=False,
        ),
    ]
