# Generated by Django 2.2.2 on 2019-06-26 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
