# Generated by Django 2.1.7 on 2019-05-25 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='assos_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='event.Association'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='assos_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='event.Association'),
        ),
        migrations.AlterField(
            model_name='president',
            name='assos_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='president', to='event.Association'),
        ),
    ]
