# Generated by Django 2.1.7 on 2019-05-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_state',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Refused'), ('C', 'Canceled')], default='P', max_length=1, verbose_name='State of the event'),
        ),
    ]
