# Generated by Django 2.1.7 on 2019-05-16 13:27

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_state',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Refused'), ('C', 'Canceled')], default='P', max_length=1, verbose_name='State of the event'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[event.models.validate_birth], verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.BooleanField(blank=True, null=True, verbose_name='Gender'),
        ),
    ]
