# Generated by Django 2.2.1 on 2019-05-28 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20190515_1615'),
        ('event', '0003_profile_image'),
    ]

    operations = [
    ]
