# Generated by Django 2.2.1 on 2019-05-29 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_merge_20190528_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='association',
            options={'permissions': (('create_event', 'User can create an event'), ('manage_member', 'User can add and remove a member'), ('choose_staff', 'User can choose staff'), ('manage_manager', 'User can add and remove managers'), ('manage_president', 'User can modify the president')), 'verbose_name': 'Association', 'verbose_name_plural': 'Associations'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': (('access_dashboard', "User can access this event's dashboard"), ('change_state', "User can the event's state")), 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
    ]
