# Generated by Django 2.2.1 on 2019-06-07 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20190529_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='manager_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.Manager'),
        ),
    ]
