# Generated by Django 2.2.1 on 2019-06-07 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20190607_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(default='E', max_length=191),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='price',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Prices', to='event.Event'),
        ),
    ]
