# Generated by Django 2.2.2 on 2019-06-15 09:53

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20190607_2305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='association',
            options={'permissions': (('create_event', 'User can create an event'), ('manage_member', 'User can add and remove a member'), ('choose_staff', 'User can choose staff'), ('manage_manager', 'User can add and remove managers')), 'verbose_name': 'Association', 'verbose_name_plural': 'Associations'},
        ),
        migrations.AlterField(
            model_name='association',
            name='name',
            field=models.CharField(max_length=64, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator], verbose_name='Name'),
        ),
    ]
