# Generated by Django 2.2.2 on 2019-06-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_auto_20190618_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='event_pics/default.jpg', null=True, upload_to='event_pics/uploads/', verbose_name="Event's cover image"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics/uploads/'),
        ),
    ]
