# Generated by Django 2.2.2 on 2019-06-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_auto_20190618_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='see_remaining',
            field=models.BooleanField(default=False, verbose_name='See remaining tickets'),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deadline to buy tickets'),
        ),
    ]
