# Generated by Django 2.2.2 on 2019-06-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_auto_20190619_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='event_pics/default.jpg', upload_to='event_pics/uploads/', verbose_name="Event's cover image"),
        ),
    ]
