# Generated by Django 2.2.2 on 2019-06-19 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_auto_20190619_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='event.Event'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='ticket_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='event.Ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='event.Event'),
        ),
    ]
