# Generated by Django 2.2.2 on 2019-06-20 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_auto_20190620_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': (('access_dashboard', "User can access this event's dashboard"), ('change_state', "User can the event's state"), ('choose_premium', 'User can make an event premium or not')), 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
    ]
