# Generated by Django 2.2.2 on 2019-06-20 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0022_boss'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': (('access_dashboard', "User can access this event's dashboard"), ('approve_event', 'User can approve of the event'), ('choose_premium', 'User can make an event premium or not'), ('cancel_event', 'User can cancel the event')), 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
    ]
