# Generated by Django 2.2.2 on 2019-06-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0024_auto_20190620_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='association',
            options={'permissions': (('create_event', 'User can create an event'), ('manage_member', 'User can add and remove a member'), ('choose_staff', 'User can choose staff'), ('manage_manager', 'User can add and remove managers'), ('modify_event', 'User can modify an event'), ('remove_event', 'User can delete an event'), ('make_event_cancelable', 'User can cancel an event'), ('validate_event', 'User can validate event and make it available for approval')), 'verbose_name': 'Association', 'verbose_name_plural': 'Associations'},
        ),
        migrations.AlterField(
            model_name='event',
            name='event_state',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Refused'), ('C', 'Canceled'), ('c', 'Canceled by the president'), ('V', 'Validated by the president')], default='P', max_length=1, verbose_name='State of the event'),
        ),
    ]
