# Generated by Django 2.2.2 on 2019-06-24 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0026_auto_20190623_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='event.Event'),
        ),
    ]
