# Generated by Django 2.2.2 on 2019-06-25 15:31

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0027_auto_20190624_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='name',
            field=models.CharField(help_text='64 characters max', max_length=64, unique=True, validators=[event.models.UnicodeValidator()], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='association',
            name='url',
            field=models.URLField(blank=True, help_text='If your association has its own website', null=True, verbose_name="Association's website"),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='event_pics/default.jpg', upload_to=event.models.get_upload_path_event, verbose_name="Event's cover image"),
        ),
        migrations.AlterField(
            model_name='event',
            name='premium_flag',
            field=models.BooleanField(default=False, help_text='Will be make it visible on the home page', verbose_name='Premium'),
        ),
        migrations.AlterField(
            model_name='event',
            name='see_remaining',
            field=models.BooleanField(default=False, help_text="if set to True, users will be able to see the remaining tickets on the event's page", verbose_name='See remaining tickets'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_deadline',
            field=models.DateTimeField(blank=True, help_text='if left empty, it is equal to start', null=True, verbose_name='Deadline to buy tickets'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='max 64 characters', max_length=64, validators=[event.models.UnicodeValidator()], verbose_name='Title of the event'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.NullBooleanField(verbose_name='Gender'),
        ),
    ]
