# Generated by Django 2.2.2 on 2019-06-25 16:53

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0028_auto_20190625_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to=event.models.get_upload_path_profile),
        ),
    ]
