# Generated by Django 2.2.2 on 2019-06-25 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0029_auto_20190625_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='manager_id',
        ),
    ]
