# Generated by Django 2.2.2 on 2019-06-26 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0031_auto_20190626_2051'),
        ('event', '0031_auto_20190626_2019'),
    ]

    operations = [
    ]
