# Generated by Django 2.2.2 on 2019-06-26 21:23

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0032_merge_20190626_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='event_pics/default.png', upload_to=event.models.get_upload_path_event, verbose_name="Event's cover image"),
        ),
    ]
